var annotated_dup =
[
    [ "std", "namespacestd.html", [
      [ "hash< BlockVertex >", "structstd_1_1hash_3_01BlockVertex_01_4.html", "structstd_1_1hash_3_01BlockVertex_01_4" ],
      [ "hash< glm::ivec2 >", "structstd_1_1hash_3_01glm_1_1ivec2_01_4.html", "structstd_1_1hash_3_01glm_1_1ivec2_01_4" ],
      [ "hash< glm::ivec3 >", "structstd_1_1hash_3_01glm_1_1ivec3_01_4.html", "structstd_1_1hash_3_01glm_1_1ivec3_01_4" ]
    ] ],
    [ "Application", "classApplication.html", "classApplication" ],
    [ "AThreadWrapper", "classAThreadWrapper.html", "classAThreadWrapper" ],
    [ "Atomic", "classAtomic.html", "classAtomic" ],
    [ "Block", "structBlock.html", null ],
    [ "BlockUpdateThread", "classBlockUpdateThread.html", "classBlockUpdateThread" ],
    [ "BlockVertex", "structBlockVertex.html", "structBlockVertex" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "Chunk", "classChunk.html", "classChunk" ],
    [ "ClientWorld", "classClientWorld.html", null ],
    [ "CreateMeshData", "classCreateMeshData.html", "classCreateMeshData" ],
    [ "Data", "structData.html", "structData" ],
    [ "DebugGui", "classDebugGui.html", "classDebugGui" ],
    [ "Descriptor", "classDescriptor.html", "classDescriptor" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "FileOutput", "classFileOutput.html", "classFileOutput" ],
    [ "History", "classHistory.html", "classHistory" ],
    [ "IdGenerator", "classIdGenerator.html", "classIdGenerator" ],
    [ "IdList", "classIdList.html", "classIdList" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "ImGuiTexture", "structImGuiTexture.html", "structImGuiTexture" ],
    [ "Input", "classInput.html", "classInput" ],
    [ "JoinThreads", "classJoinThreads.html", "classJoinThreads" ],
    [ "LineVertex", "structLineVertex.html", "structLineVertex" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Mesh", "structMesh.html", "structMesh" ],
    [ "ModelMatrice", "structModelMatrice.html", "structModelMatrice" ],
    [ "ModelMatrix_push_constant", "structModelMatrix__push__constant.html", "structModelMatrix__push__constant" ],
    [ "Perlin", "classPerlin.html", "classPerlin" ],
    [ "Pipeline", "classPipeline.html", "classPipeline" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", "structQueueFamilyIndices" ],
    [ "RenderThread", "classRenderThread.html", "classRenderThread" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "ShadowMapLight", "structShadowMapLight.html", "structShadowMapLight" ],
    [ "SingleTimeCommand", "classSingleTimeCommand.html", "classSingleTimeCommand" ],
    [ "Status", "classStatus.html", "classStatus" ],
    [ "Swapchain", "classSwapchain.html", "classSwapchain" ],
    [ "ThreadPool", "classThreadPool.html", "classThreadPool" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Transform", "classTransform.html", "classTransform" ],
    [ "UpdateThread", "classUpdateThread.html", "classUpdateThread" ],
    [ "ViewFrustum", "classViewFrustum.html", "classViewFrustum" ],
    [ "ViewProjMatrices", "structViewProjMatrices.html", "structViewProjMatrices" ],
    [ "VulaknMemoryAllocator", "classVulaknMemoryAllocator.html", "classVulaknMemoryAllocator" ],
    [ "VulkanAPI", "classVulkanAPI.html", "classVulkanAPI" ],
    [ "Window", "classWindow.html", "classWindow" ],
    [ "World", "classWorld.html", "classWorld" ],
    [ "WorldGenerator", "classWorldGenerator.html", "classWorldGenerator" ],
    [ "WorldScene", "classWorldScene.html", "classWorldScene" ]
];