var annotated_dup =
[
    [ "Event", "namespaceEvent.html", [
      [ "AbstractEvent", "classEvent_1_1AbstractEvent.html", "classEvent_1_1AbstractEvent" ],
      [ "HandlerWrapper", "classEvent_1_1HandlerWrapper.html", "classEvent_1_1HandlerWrapper" ],
      [ "HandlerWrapperInterface", "classEvent_1_1HandlerWrapperInterface.html", "classEvent_1_1HandlerWrapperInterface" ],
      [ "Manager", "classEvent_1_1Manager.html", "classEvent_1_1Manager" ],
      [ "PlayerMoving", "classEvent_1_1PlayerMoving.html", "classEvent_1_1PlayerMoving" ]
    ] ],
    [ "Sound", "namespaceSound.html", [
      [ "Data", "classSound_1_1Data.html", "classSound_1_1Data" ],
      [ "DataChunk", "structSound_1_1DataChunk.html", "structSound_1_1DataChunk" ],
      [ "Engine", "classSound_1_1Engine.html", "classSound_1_1Engine" ],
      [ "FMTChunk", "structSound_1_1FMTChunk.html", "structSound_1_1FMTChunk" ],
      [ "Instance", "structSound_1_1Instance.html", "structSound_1_1Instance" ],
      [ "RIFFChunk", "structSound_1_1RIFFChunk.html", "structSound_1_1RIFFChunk" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Chunk::genLevel >", "structstd_1_1hash_3_01Chunk_1_1genLevel_01_4.html", "structstd_1_1hash_3_01Chunk_1_1genLevel_01_4" ],
      [ "hash< glm::ivec2 >", "structstd_1_1hash_3_01glm_1_1ivec2_01_4.html", "structstd_1_1hash_3_01glm_1_1ivec2_01_4" ],
      [ "hash< glm::ivec3 >", "structstd_1_1hash_3_01glm_1_1ivec3_01_4.html", "structstd_1_1hash_3_01glm_1_1ivec3_01_4" ],
      [ "hash< ObjVertex >", "structstd_1_1hash_3_01ObjVertex_01_4.html", "structstd_1_1hash_3_01ObjVertex_01_4" ],
      [ "hash< ServerWorld::Ticket >", "structstd_1_1hash_3_01ServerWorld_1_1Ticket_01_4.html", "structstd_1_1hash_3_01ServerWorld_1_1Ticket_01_4" ],
      [ "hash< std::pair< glm::ivec3, Chunk::genLevel > >", "structstd_1_1hash_3_01std_1_1pair_3_01glm_1_1ivec3_00_01Chunk_1_1genLevel_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1pair_3_01glm_1_1ivec3_00_01Chunk_1_1genLevel_01_4_01_4" ]
    ] ],
    [ "task", "namespacetask.html", [
      [ "BaseError", "classtask_1_1BaseError.html", "classtask_1_1BaseError" ],
      [ "CycleError", "classtask_1_1CycleError.html", "classtask_1_1CycleError" ],
      [ "EmptyGraphError", "classtask_1_1EmptyGraphError.html", "classtask_1_1EmptyGraphError" ],
      [ "EmptyModuleError", "classtask_1_1EmptyModuleError.html", "classtask_1_1EmptyModuleError" ],
      [ "Executor", "classtask_1_1Executor.html", "classtask_1_1Executor" ],
      [ "Future", "classtask_1_1Future.html", "classtask_1_1Future" ],
      [ "Graph", "classtask_1_1Graph.html", "classtask_1_1Graph" ],
      [ "Task", "classtask_1_1Task.html", "classtask_1_1Task" ],
      [ "TaskGraph", "classtask_1_1TaskGraph.html", "classtask_1_1TaskGraph" ],
      [ "TaskNode", "classtask_1_1TaskNode.html", "classtask_1_1TaskNode" ],
      [ "TaskNotFromSameGraphError", "classtask_1_1TaskNotFromSameGraphError.html", "classtask_1_1TaskNotFromSameGraphError" ]
    ] ],
    [ "Application", "classApplication.html", "classApplication" ],
    [ "AtmosphereParams", "structAtmosphereParams.html", "structAtmosphereParams" ],
    [ "Atomic", "classAtomic.html", "classAtomic" ],
    [ "BlockActionPacket", "classBlockActionPacket.html", "classBlockActionPacket" ],
    [ "BlockInfo", "classBlockInfo.html", "classBlockInfo" ],
    [ "BlocksInfo", "classBlocksInfo.html", "classBlocksInfo" ],
    [ "BlockUpdateThread", "classBlockUpdateThread.html", "classBlockUpdateThread" ],
    [ "BlockVertex", "structBlockVertex.html", "structBlockVertex" ],
    [ "Buffer", "classBuffer.html", "classBuffer" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "Chunk", "classChunk.html", "classChunk" ],
    [ "ChunkMeshRenderData", "structChunkMeshRenderData.html", "structChunkMeshRenderData" ],
    [ "ChunkPacket", "classChunkPacket.html", "classChunkPacket" ],
    [ "ChunkRequestPacket", "classChunkRequestPacket.html", "classChunkRequestPacket" ],
    [ "ChunkUnloadPacket", "classChunkUnloadPacket.html", "classChunkUnloadPacket" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "ClientSocket", "classClientSocket.html", "classClientSocket" ],
    [ "ClientWorld", "classClientWorld.html", "classClientWorld" ],
    [ "Connection", "classConnection.html", "classConnection" ],
    [ "ConnectionPacket", "classConnectionPacket.html", "classConnectionPacket" ],
    [ "ConnectionSocket", "classConnectionSocket.html", "classConnectionSocket" ],
    [ "CreateMeshData", "classCreateMeshData.html", "classCreateMeshData" ],
    [ "DebugGui", "classDebugGui.html", "classDebugGui" ],
    [ "Descriptor", "classDescriptor.html", "classDescriptor" ],
    [ "DisconnectPacket", "classDisconnectPacket.html", "classDisconnectPacket" ],
    [ "ECS", "classECS.html", "classECS" ],
    [ "EntityMovePacket", "classEntityMovePacket.html", null ],
    [ "EntityVertex", "structEntityVertex.html", "structEntityVertex" ],
    [ "Face", "structFace.html", "structFace" ],
    [ "FileOutput", "classFileOutput.html", "classFileOutput" ],
    [ "FrustumPoints", "structFrustumPoints.html", "structFrustumPoints" ],
    [ "GlobalDescriptorWrite", "structGlobalDescriptorWrite.html", "structGlobalDescriptorWrite" ],
    [ "GlobalPushConstant", "structGlobalPushConstant.html", "structGlobalPushConstant" ],
    [ "History", "classHistory.html", "classHistory" ],
    [ "HitBox", "classHitBox.html", "classHitBox" ],
    [ "IdGenerator", "classIdGenerator.html", "classIdGenerator" ],
    [ "IdList", "classIdList.html", "classIdList" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "ImGuiTexture", "structImGuiTexture.html", "structImGuiTexture" ],
    [ "Input", "classInput.html", "classInput" ],
    [ "IPacket", "classIPacket.html", "classIPacket" ],
    [ "ItemInfo", "classItemInfo.html", "classItemInfo" ],
    [ "ItemsInfo", "classItemsInfo.html", "classItemsInfo" ],
    [ "ItemVertex", "structItemVertex.html", "structItemVertex" ],
    [ "JoinThreads", "classJoinThreads.html", "classJoinThreads" ],
    [ "LineVertex", "structLineVertex.html", "structLineVertex" ],
    [ "LoadDistancePacket", "classLoadDistancePacket.html", "classLoadDistancePacket" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Mat4", "classMat4.html", "classMat4" ],
    [ "Mesh", "structMesh.html", "structMesh" ],
    [ "MeshRenderData", "structMeshRenderData.html", "structMeshRenderData" ],
    [ "Mob", "classMob.html", "classMob" ],
    [ "ModelMatrix_push_constant", "structModelMatrix__push__constant.html", "structModelMatrix__push__constant" ],
    [ "NetworkThread", "classNetworkThread.html", "classNetworkThread" ],
    [ "ObjLoader", "classObjLoader.html", "classObjLoader" ],
    [ "ObjVertex", "structObjVertex.html", "structObjVertex" ],
    [ "PacketFactory", "classPacketFactory.html", "classPacketFactory" ],
    [ "Perlin", "classPerlin.html", "classPerlin" ],
    [ "PingPacket", "classPingPacket.html", "classPingPacket" ],
    [ "Pipeline", "classPipeline.html", "classPipeline" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerConnectedPacket", "classPlayerConnectedPacket.html", "classPlayerConnectedPacket" ],
    [ "PlayerListPacket", "classPlayerListPacket.html", "classPlayerListPacket" ],
    [ "PlayerModel", "classPlayerModel.html", "classPlayerModel" ],
    [ "PlayerMovePacket", "classPlayerMovePacket.html", "classPlayerMovePacket" ],
    [ "PlayerRenderData", "structPlayerRenderData.html", "structPlayerRenderData" ],
    [ "Poller", "classPoller.html", "classPoller" ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", "structQueueFamilyIndices" ],
    [ "RayCastOnBlockResult", "structRayCastOnBlockResult.html", "structRayCastOnBlockResult" ],
    [ "RenderThread", "classRenderThread.html", "classRenderThread" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "ServerBlockUpdateThread", "classServerBlockUpdateThread.html", "classServerBlockUpdateThread" ],
    [ "ServerSocket", "classServerSocket.html", "classServerSocket" ],
    [ "ServerWorld", "classServerWorld.html", "classServerWorld" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "ShadowMapLight", "structShadowMapLight.html", "structShadowMapLight" ],
    [ "SingleTimeCommand", "classSingleTimeCommand.html", "classSingleTimeCommand" ],
    [ "Socket", "classSocket.html", "classSocket" ],
    [ "Status", "classStatus.html", "classStatus" ],
    [ "StructureInfo", "classStructureInfo.html", "classStructureInfo" ],
    [ "StructuresInfo", "classStructuresInfo.html", "classStructuresInfo" ],
    [ "Swapchain", "classSwapchain.html", "classSwapchain" ],
    [ "test", "structtest.html", "structtest" ],
    [ "TextRenderer", "classTextRenderer.html", "classTextRenderer" ],
    [ "ThreadPool", "classThreadPool.html", "classThreadPool" ],
    [ "ThreadPoolAccessor", "classThreadPoolAccessor.html", "classThreadPoolAccessor" ],
    [ "ThreadSafeQueue", "classThreadSafeQueue.html", "classThreadSafeQueue" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Transform", "classTransform.html", "classTransform" ],
    [ "UBO", "structUBO.html", "structUBO" ],
    [ "UpdateThread", "classUpdateThread.html", "classUpdateThread" ],
    [ "ViewFrustum", "classViewFrustum.html", "classViewFrustum" ],
    [ "ViewProjMatrices", "structViewProjMatrices.html", "structViewProjMatrices" ],
    [ "VulkanAPI", "classVulkanAPI.html", "classVulkanAPI" ],
    [ "VulkanMemoryAllocator", "classVulkanMemoryAllocator.html", "classVulkanMemoryAllocator" ],
    [ "Window", "classWindow.html", "classWindow" ],
    [ "World", "classWorld.html", "classWorld" ]
];