var hierarchy =
[
    [ "Event::AbstractEvent", "classEvent_1_1AbstractEvent.html", [
      [ "Event::PlayerMoving", "classEvent_1_1PlayerMoving.html", null ]
    ] ],
    [ "Application", "classApplication.html", null ],
    [ "task::Executor::info::AsyncInfo", "structtask_1_1Executor_1_1info_1_1AsyncInfo.html", null ],
    [ "AtmosphereParams", "structAtmosphereParams.html", null ],
    [ "Atomic< T >", "classAtomic.html", null ],
    [ "Atomic< glm::vec3 >", "classAtomic.html", null ],
    [ "PlayerModel::AttackAnimation", "classPlayerModel_1_1AttackAnimation.html", null ],
    [ "bar< EntityType, ComponentType >", "classbar.html", null ],
    [ "Chunk::biomeInfo", "structChunk_1_1biomeInfo.html", null ],
    [ "BlockInfo", "classBlockInfo.html", null ],
    [ "BlocksInfo", "classBlocksInfo.html", null ],
    [ "ServerWorld::BlockUpdateData", "structServerWorld_1_1BlockUpdateData.html", null ],
    [ "BlockUpdateThread", "classBlockUpdateThread.html", null ],
    [ "BlockVertex", "structBlockVertex.html", null ],
    [ "Buffer", "classBuffer.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "Chunk", "classChunk.html", null ],
    [ "ChunkData", "structChunkData.html", null ],
    [ "ChunkPacket::ChunkData", "structChunkPacket_1_1ChunkData.html", null ],
    [ "ServerWorld::ChunkLoadUnloadData", "structServerWorld_1_1ChunkLoadUnloadData.html", null ],
    [ "RenderAPI::ChunkMeshCreateInfo", "structRenderAPI_1_1ChunkMeshCreateInfo.html", null ],
    [ "ChunkRenderData", "structChunkRenderData.html", null ],
    [ "Client", "classClient.html", null ],
    [ "Connection", "classConnection.html", null ],
    [ "Buffer::CreateInfo", "structBuffer_1_1CreateInfo.html", null ],
    [ "Descriptor::CreateInfo", "structDescriptor_1_1CreateInfo.html", null ],
    [ "Image::CreateInfo", "structImage_1_1CreateInfo.html", null ],
    [ "Pipeline::CreateInfo", "structPipeline_1_1CreateInfo.html", null ],
    [ "Swapchain::CreateInfo", "structSwapchain_1_1CreateInfo.html", null ],
    [ "CreateMeshData", "classCreateMeshData.html", null ],
    [ "Sound::Data", "classSound_1_1Data.html", null ],
    [ "Sound::DataChunk", "structSound_1_1DataChunk.html", null ],
    [ "DebugGui", "classDebugGui.html", null ],
    [ "Descriptor", "classDescriptor.html", null ],
    [ "ECS", "classECS.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "task::TaskGraph", "classtask_1_1TaskGraph.html", null ]
    ] ],
    [ "Sound::Engine", "classSound_1_1Engine.html", null ],
    [ "EntityVertex", "structEntityVertex.html", null ],
    [ "std::exception", null, [
      [ "Client::ServerDisconnected", "classClient_1_1ServerDisconnected.html", null ],
      [ "Save::Region::CorruptedFileException", "classSave_1_1Region_1_1CorruptedFileException.html", null ],
      [ "Server::ClientDisconnected", "classServer_1_1ClientDisconnected.html", null ],
      [ "ecs::Manager< entityType >::ComponentAlreadyExists", "classecs_1_1Manager_1_1ComponentAlreadyExists.html", null ],
      [ "ecs::Manager< entityType >::ComponentDoesNotExist", "classecs_1_1Manager_1_1ComponentDoesNotExist.html", null ],
      [ "ecs::Manager< entityType >::EntityAlreadyExists", "classecs_1_1Manager_1_1EntityAlreadyExists.html", null ],
      [ "ecs::Manager< entityType >::EntityDoesNotExist", "classecs_1_1Manager_1_1EntityDoesNotExist.html", null ],
      [ "task::BaseError", "classtask_1_1BaseError.html", [
        [ "task::CycleError", "classtask_1_1CycleError.html", null ],
        [ "task::EmptyGraphError", "classtask_1_1EmptyGraphError.html", null ],
        [ "task::EmptyModuleError", "classtask_1_1EmptyModuleError.html", null ],
        [ "task::TaskNotFromSameGraphError", "classtask_1_1TaskNotFromSameGraphError.html", null ]
      ] ]
    ] ],
    [ "task::Executor", "classtask_1_1Executor.html", null ],
    [ "ExecutorAccessor", "classExecutorAccessor.html", null ],
    [ "Face", "structFace.html", null ],
    [ "Sound::FMTChunk", "structSound_1_1FMTChunk.html", null ],
    [ "FrustumPoints", "structFrustumPoints.html", null ],
    [ "std::future", null, [
      [ "task::Future< T >", "classtask_1_1Future.html", null ]
    ] ],
    [ "GlobalDescriptorWrite", "structGlobalDescriptorWrite.html", null ],
    [ "GlobalPushConstant", "structGlobalPushConstant.html", null ],
    [ "task::Graph", "classtask_1_1Graph.html", null ],
    [ "task::Executor::info::GraphInfo", "structtask_1_1Executor_1_1info_1_1GraphInfo.html", null ],
    [ "Event::HandlerWrapperInterface", "classEvent_1_1HandlerWrapperInterface.html", [
      [ "Event::HandlerWrapper< EventType >", "classEvent_1_1HandlerWrapper.html", null ]
    ] ],
    [ "ServerWorld::Ticket::hash", "structServerWorld_1_1Ticket_1_1hash.html", null ],
    [ "std::hash< Chunk::genLevel >", "structstd_1_1hash_3_01Chunk_1_1genLevel_01_4.html", null ],
    [ "std::hash< glm::ivec2 >", "structstd_1_1hash_3_01glm_1_1ivec2_01_4.html", null ],
    [ "std::hash< glm::ivec3 >", "structstd_1_1hash_3_01glm_1_1ivec3_01_4.html", null ],
    [ "std::hash< ObjVertex >", "structstd_1_1hash_3_01ObjVertex_01_4.html", null ],
    [ "std::hash< ServerWorld::Ticket >", "structstd_1_1hash_3_01ServerWorld_1_1Ticket_01_4.html", null ],
    [ "std::hash< std::pair< glm::ivec3, Chunk::genLevel > >", "structstd_1_1hash_3_01std_1_1pair_3_01glm_1_1ivec3_00_01Chunk_1_1genLevel_01_4_01_4.html", null ],
    [ "History< T, N >", "classHistory.html", null ],
    [ "History< float, 100 >", "classHistory.html", null ],
    [ "History< float, 1000 >", "classHistory.html", null ],
    [ "History< size_t, 100 >", "classHistory.html", null ],
    [ "HitBox", "classHitBox.html", null ],
    [ "IdGenerator< IdType >", "classIdGenerator.html", null ],
    [ "IdGenerator< Key >", "classIdGenerator.html", null ],
    [ "Image", "classImage.html", null ],
    [ "ImGuiTexture", "structImGuiTexture.html", null ],
    [ "ecs::IndexOf< Args >", "structecs_1_1IndexOf.html", null ],
    [ "Input", "classInput.html", null ],
    [ "Sound::Instance", "structSound_1_1Instance.html", null ],
    [ "InstanceData", "structInstanceData.html", null ],
    [ "IPacket", "classIPacket.html", [
      [ "BlockActionPacket", "classBlockActionPacket.html", null ],
      [ "ChunkPacket", "classChunkPacket.html", null ],
      [ "ChunkRequestPacket", "classChunkRequestPacket.html", null ],
      [ "ChunkUnloadPacket", "classChunkUnloadPacket.html", null ],
      [ "ConnectionPacket", "classConnectionPacket.html", null ],
      [ "DisconnectPacket", "classDisconnectPacket.html", null ],
      [ "LoadDistancePacket", "classLoadDistancePacket.html", null ],
      [ "PingPacket", "classPingPacket.html", null ],
      [ "PlayerConnectedPacket", "classPlayerConnectedPacket.html", null ],
      [ "PlayerListPacket", "classPlayerListPacket.html", null ],
      [ "PlayerMovePacket", "classPlayerMovePacket.html", null ]
    ] ],
    [ "IServerToClientPacket", null, [
      [ "EntityMovePacket", "classEntityMovePacket.html", null ]
    ] ],
    [ "ItemInfo", "classItemInfo.html", null ],
    [ "ItemsInfo", "classItemsInfo.html", null ],
    [ "ItemVertex", "structItemVertex.html", null ],
    [ "JoinThreads", "classJoinThreads.html", null ],
    [ "LineVertex", "structLineVertex.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "ecs::Manager< entityType >", "classecs_1_1Manager.html", null ],
    [ "Event::Manager", "classEvent_1_1Manager.html", null ],
    [ "Mat4", "classMat4.html", null ],
    [ "MemoryRange", "classMemoryRange.html", null ],
    [ "Mesh", "structMesh.html", null ],
    [ "mesh", "structmesh.html", null ],
    [ "MeshRenderData", "structMeshRenderData.html", null ],
    [ "Mob", "classMob.html", null ],
    [ "ModelMatrix_push_constant", "structModelMatrix__push__constant.html", null ],
    [ "NetworkThread", "classNetworkThread.html", null ],
    [ "task::Executor::info::NodeInfo", "structtask_1_1Executor_1_1info_1_1NodeInfo.html", null ],
    [ "ObjLoader", "classObjLoader.html", null ],
    [ "ObjVertex", "structObjVertex.html", null ],
    [ "std::ofstream", null, [
      [ "FileOutput", "classFileOutput.html", null ]
    ] ],
    [ "PacketFactory", "classPacketFactory.html", null ],
    [ "Perlin", "classPerlin.html", null ],
    [ "Pipeline", "classPipeline.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "PlayerListPacket::PlayerInfo", "structPlayerListPacket_1_1PlayerInfo.html", null ],
    [ "PlayerModel", "classPlayerModel.html", null ],
    [ "PlayerRenderData", "structPlayerRenderData.html", null ],
    [ "ClientWorld::PlayerUseResult", "structClientWorld_1_1PlayerUseResult.html", null ],
    [ "Poller", "classPoller.html", null ],
    [ "Position", "structPosition.html", null ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", null ],
    [ "RayCastOnBlockResult", "structRayCastOnBlockResult.html", null ],
    [ "RenderAPI", "classRenderAPI.html", null ],
    [ "Camera::RenderInfo", "structCamera_1_1RenderInfo.html", null ],
    [ "RenderThread", "classRenderThread.html", null ],
    [ "Sound::RIFFChunk", "structSound_1_1RIFFChunk.html", null ],
    [ "RLE_TEST< T >", "classRLE__TEST.html", null ],
    [ "Save", "classSave.html", null ],
    [ "Client::sendInfo", "structClient_1_1sendInfo.html", null ],
    [ "Server::sendInfo", "structServer_1_1sendInfo.html", null ],
    [ "Server", "classServer.html", null ],
    [ "ServerBlockUpdateThread", "classServerBlockUpdateThread.html", null ],
    [ "Settings", "classSettings.html", null ],
    [ "ShadowMapLight", "structShadowMapLight.html", null ],
    [ "SingleTimeCommand", "classSingleTimeCommand.html", null ],
    [ "Socket", "classSocket.html", [
      [ "ClientSocket", "classClientSocket.html", null ],
      [ "ConnectionSocket", "classConnectionSocket.html", null ],
      [ "ServerSocket", "classServerSocket.html", null ]
    ] ],
    [ "ecs::SparseSet< entityType >", "classecs_1_1SparseSet.html", null ],
    [ "ecs::SparseSet< EntityType >", "classecs_1_1SparseSet.html", [
      [ "ecs::ComponentStorage< EntityType, ComponentType >", "classecs_1_1ComponentStorage.html", null ]
    ] ],
    [ "ecs::SparseSetNode< entityType, ComponentType >", "structecs_1_1SparseSetNode.html", null ],
    [ "Status", "classStatus.html", null ],
    [ "StructureInfo", "classStructureInfo.html", null ],
    [ "StructuresInfo", "classStructuresInfo.html", null ],
    [ "Swapchain::SupportDetails", "structSwapchain_1_1SupportDetails.html", null ],
    [ "Swapchain", "classSwapchain.html", null ],
    [ "task::Task", "classtask_1_1Task.html", null ],
    [ "task::TaskNode", "classtask_1_1TaskNode.html", null ],
    [ "Test< EntityType, ComponentTypes >", "classTest.html", null ],
    [ "test", "structtest.html", null ],
    [ "TextRenderer", "classTextRenderer.html", null ],
    [ "ThreadPool", "classThreadPool.html", null ],
    [ "ThreadPoolAccessor", "classThreadPoolAccessor.html", null ],
    [ "ThreadSafeQueue< T >", "classThreadSafeQueue.html", null ],
    [ "ThreadSafeQueue< Server::sendInfo >", "classThreadSafeQueue.html", null ],
    [ "ThreadSafeQueue< std::shared_ptr< IPacket > >", "classThreadSafeQueue.html", null ],
    [ "ServerWorld::Ticket", "structServerWorld_1_1Ticket.html", null ],
    [ "Timer< ChronoCount, HistorySize >", "classTimer.html", null ],
    [ "Transform", "classTransform.html", null ],
    [ "transform", "structtransform.html", null ],
    [ "UBO", "structUBO.html", null ],
    [ "std::unordered_map", null, [
      [ "IdList< Key, Value, container, IdGen >", "classIdList.html", null ]
    ] ],
    [ "UpdateThread", "classUpdateThread.html", null ],
    [ "Velocity", "structVelocity.html", null ],
    [ "PlayerModel::Vertex", "structPlayerModel_1_1Vertex.html", null ],
    [ "ecs::View< EntityType, ComponentTypes >", "classecs_1_1View.html", null ],
    [ "ViewFrustum", "classViewFrustum.html", null ],
    [ "ecs::ViewIterator< EntityType, pool_size >", "classecs_1_1ViewIterator.html", null ],
    [ "ViewProjMatrices", "structViewProjMatrices.html", null ],
    [ "VulkanMemoryAllocator", "classVulkanMemoryAllocator.html", null ],
    [ "PlayerModel::WalkAnimation", "classPlayerModel_1_1WalkAnimation.html", null ],
    [ "Window", "classWindow.html", null ],
    [ "World", "classWorld.html", [
      [ "ClientWorld", "classClientWorld.html", null ],
      [ "ServerWorld", "classServerWorld.html", null ]
    ] ],
    [ "World::WorldGenerator", "classWorld_1_1WorldGenerator.html", null ]
];