var hierarchy =
[
    [ "Application", "classApplication.html", null ],
    [ "Atomic< T >", "classAtomic.html", null ],
    [ "Atomic< glm::vec3 >", "classAtomic.html", null ],
    [ "Block", "structBlock.html", null ],
    [ "BlockUpdateThread", "classBlockUpdateThread.html", null ],
    [ "BlockVertex", "structBlockVertex.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "Chunk", "classChunk.html", null ],
    [ "ClientWorld", "classClientWorld.html", null ],
    [ "Descriptor::CreateInfo", "structDescriptor_1_1CreateInfo.html", null ],
    [ "Image::CreateInfo", "structImage_1_1CreateInfo.html", null ],
    [ "Pipeline::CreateInfo", "structPipeline_1_1CreateInfo.html", null ],
    [ "Swapchain::CreateInfo", "structSwapchain_1_1CreateInfo.html", null ],
    [ "CreateMeshData", "classCreateMeshData.html", null ],
    [ "Data", "structData.html", null ],
    [ "DebugGui", "classDebugGui.html", null ],
    [ "Descriptor", "classDescriptor.html", null ],
    [ "ECS", "classECS.html", null ],
    [ "EntityMatrices", "structEntityMatrices.html", null ],
    [ "EntityVertex", "structEntityVertex.html", null ],
    [ "std::hash< BlockVertex >", "structstd_1_1hash_3_01BlockVertex_01_4.html", null ],
    [ "std::hash< glm::ivec2 >", "structstd_1_1hash_3_01glm_1_1ivec2_01_4.html", null ],
    [ "std::hash< glm::ivec3 >", "structstd_1_1hash_3_01glm_1_1ivec3_01_4.html", null ],
    [ "History< T, N >", "classHistory.html", null ],
    [ "History< float, 100 >", "classHistory.html", null ],
    [ "History< float, 1000 >", "classHistory.html", null ],
    [ "HitBox", "classHitBox.html", null ],
    [ "IdGenerator< IdType >", "classIdGenerator.html", null ],
    [ "IdGenerator< Key >", "classIdGenerator.html", null ],
    [ "IdGenerator< uint64_t >", "classIdGenerator.html", null ],
    [ "Image", "classImage.html", null ],
    [ "ImGuiTexture", "structImGuiTexture.html", null ],
    [ "Input", "classInput.html", null ],
    [ "JoinThreads", "classJoinThreads.html", null ],
    [ "LineVertex", "structLineVertex.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "Mesh", "structMesh.html", null ],
    [ "WorldScene::MeshList", "classWorldScene_1_1MeshList.html", null ],
    [ "WorldScene::MeshRenderData", "structWorldScene_1_1MeshRenderData.html", null ],
    [ "ModelMatrice", "structModelMatrice.html", null ],
    [ "ModelMatrix_push_constant", "structModelMatrix__push__constant.html", null ],
    [ "std::ofstream", null, [
      [ "FileOutput", "classFileOutput.html", null ]
    ] ],
    [ "Perlin", "classPerlin.html", null ],
    [ "Pipeline", "classPipeline.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", null ],
    [ "Camera::RenderInfo", "structCamera_1_1RenderInfo.html", null ],
    [ "RenderThread", "classRenderThread.html", null ],
    [ "Settings", "classSettings.html", null ],
    [ "ShadowMapLight", "structShadowMapLight.html", null ],
    [ "SingleTimeCommand", "classSingleTimeCommand.html", null ],
    [ "Status", "classStatus.html", null ],
    [ "Swapchain::SupportDetails", "structSwapchain_1_1SupportDetails.html", null ],
    [ "Swapchain", "classSwapchain.html", null ],
    [ "ThreadPool", "classThreadPool.html", null ],
    [ "Timer< ChronoCount, HistorySize >", "classTimer.html", null ],
    [ "Transform", "classTransform.html", null ],
    [ "std::unordered_map", null, [
      [ "IdList< uint64_t, Mesh >", "classIdList.html", null ],
      [ "IdList< uint64_t, std::shared_ptr< Player > >", "classIdList.html", null ],
      [ "IdList< uint64_t, WorldScene::MeshRenderData >", "classIdList.html", null ],
      [ "IdList< Key, Value, container, IdGen >", "classIdList.html", null ]
    ] ],
    [ "UpdateThread", "classUpdateThread.html", null ],
    [ "ViewFrustum", "classViewFrustum.html", null ],
    [ "ViewProjMatrices", "structViewProjMatrices.html", null ],
    [ "VulaknMemoryAllocator", "classVulaknMemoryAllocator.html", null ],
    [ "VulkanAPI", "classVulkanAPI.html", null ],
    [ "Window", "classWindow.html", null ],
    [ "World", "classWorld.html", null ],
    [ "WorldGenerator", "classWorldGenerator.html", null ],
    [ "WorldScene", "classWorldScene.html", null ]
];