var hierarchy =
[
    [ "Event::AbstractEvent", "classEvent_1_1AbstractEvent.html", [
      [ "Event::PlayerMoving", "classEvent_1_1PlayerMoving.html", null ]
    ] ],
    [ "Application", "classApplication.html", null ],
    [ "AtmosphereParams", "structAtmosphereParams.html", null ],
    [ "Atomic< T >", "classAtomic.html", null ],
    [ "Atomic< glm::vec3 >", "classAtomic.html", null ],
    [ "PlayerModel::AttackAnimation", "classPlayerModel_1_1AttackAnimation.html", null ],
    [ "BlockInfo", "classBlockInfo.html", null ],
    [ "BlocksInfo", "classBlocksInfo.html", null ],
    [ "ServerWorld::BlockUpdateData", "structServerWorld_1_1BlockUpdateData.html", null ],
    [ "BlockUpdateThread", "classBlockUpdateThread.html", null ],
    [ "BlockVertex", "structBlockVertex.html", null ],
    [ "Buffer", "classBuffer.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "Chunk", "classChunk.html", null ],
    [ "ChunkPacket::ChunkData", "structChunkPacket_1_1ChunkData.html", null ],
    [ "ServerWorld::ChunkLoadUnloadData", "structServerWorld_1_1ChunkLoadUnloadData.html", null ],
    [ "WorldScene::ChunkMeshRenderData", "structWorldScene_1_1ChunkMeshRenderData.html", null ],
    [ "Client", "classClient.html", null ],
    [ "ClientPacketHandler", "classClientPacketHandler.html", null ],
    [ "Connection", "classConnection.html", null ],
    [ "Buffer::CreateInfo", "structBuffer_1_1CreateInfo.html", null ],
    [ "Descriptor::CreateInfo", "structDescriptor_1_1CreateInfo.html", null ],
    [ "Image::CreateInfo", "structImage_1_1CreateInfo.html", null ],
    [ "Pipeline::CreateInfo", "structPipeline_1_1CreateInfo.html", null ],
    [ "Swapchain::CreateInfo", "structSwapchain_1_1CreateInfo.html", null ],
    [ "CreateMeshData", "classCreateMeshData.html", null ],
    [ "Sound::Data", "classSound_1_1Data.html", null ],
    [ "Sound::DataChunk", "structSound_1_1DataChunk.html", null ],
    [ "WorldScene::DebugBlock", "structWorldScene_1_1DebugBlock.html", null ],
    [ "DebugGui", "classDebugGui.html", null ],
    [ "Descriptor", "classDescriptor.html", null ],
    [ "ECS", "classECS.html", null ],
    [ "Sound::Engine", "classSound_1_1Engine.html", null ],
    [ "EntityMatrices", "structEntityMatrices.html", null ],
    [ "EntityVertex", "structEntityVertex.html", null ],
    [ "std::exception", null, [
      [ "Client::ServerDisconnected", "classClient_1_1ServerDisconnected.html", null ],
      [ "Server::ClientDisconnected", "classServer_1_1ClientDisconnected.html", null ]
    ] ],
    [ "Face", "structFace.html", null ],
    [ "Sound::FMTChunk", "structSound_1_1FMTChunk.html", null ],
    [ "WorldGenerator::genInfo", "structWorldGenerator_1_1genInfo.html", null ],
    [ "Event::HandlerWrapperInterface", "classEvent_1_1HandlerWrapperInterface.html", [
      [ "Event::HandlerWrapper< EventType >", "classEvent_1_1HandlerWrapper.html", null ]
    ] ],
    [ "ServerWorld::Ticket::hash", "structServerWorld_1_1Ticket_1_1hash.html", null ],
    [ "std::hash< BlockVertex >", "structstd_1_1hash_3_01BlockVertex_01_4.html", null ],
    [ "std::hash< glm::ivec2 >", "structstd_1_1hash_3_01glm_1_1ivec2_01_4.html", null ],
    [ "std::hash< glm::ivec3 >", "structstd_1_1hash_3_01glm_1_1ivec3_01_4.html", null ],
    [ "std::hash< ObjVertex >", "structstd_1_1hash_3_01ObjVertex_01_4.html", null ],
    [ "std::hash< ServerWorld::Ticket >", "structstd_1_1hash_3_01ServerWorld_1_1Ticket_01_4.html", null ],
    [ "History< T, N >", "classHistory.html", null ],
    [ "History< float, 100 >", "classHistory.html", null ],
    [ "History< float, 1000 >", "classHistory.html", null ],
    [ "History< size_t, 100 >", "classHistory.html", null ],
    [ "HitBox", "classHitBox.html", null ],
    [ "IdGenerator< IdType >", "classIdGenerator.html", null ],
    [ "IdGenerator< Key >", "classIdGenerator.html", null ],
    [ "IdGenerator< uint64_t >", "classIdGenerator.html", null ],
    [ "Image", "classImage.html", null ],
    [ "ImGuiTexture", "structImGuiTexture.html", null ],
    [ "IncomingPacketList", "classIncomingPacketList.html", null ],
    [ "Input", "classInput.html", null ],
    [ "Sound::Instance", "structSound_1_1Instance.html", null ],
    [ "IPacket", "classIPacket.html", [
      [ "BlockActionPacket", "classBlockActionPacket.html", null ],
      [ "ChunkPacket", "classChunkPacket.html", null ],
      [ "ChunkRequestPacket", "classChunkRequestPacket.html", null ],
      [ "ChunkUnloadPacket", "classChunkUnloadPacket.html", null ],
      [ "ConnectionPacket", "classConnectionPacket.html", null ],
      [ "DisconnectPacket", "classDisconnectPacket.html", null ],
      [ "PingPacket", "classPingPacket.html", null ],
      [ "PlayerConnectedPacket", "classPlayerConnectedPacket.html", null ],
      [ "PlayerListPacket", "classPlayerListPacket.html", null ],
      [ "PlayerMovePacket", "classPlayerMovePacket.html", null ]
    ] ],
    [ "IServerToClientPacket", null, [
      [ "EntityMovePacket", "classEntityMovePacket.html", null ]
    ] ],
    [ "ItemIconPushConstant", "structItemIconPushConstant.html", null ],
    [ "ItemInfo", "classItemInfo.html", null ],
    [ "ItemsInfo", "classItemsInfo.html", null ],
    [ "ItemVertex", "structItemVertex.html", null ],
    [ "JoinThreads", "classJoinThreads.html", null ],
    [ "LineVertex", "structLineVertex.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "Event::Manager", "classEvent_1_1Manager.html", null ],
    [ "Mat4", "classMat4.html", null ],
    [ "Mesh", "structMesh.html", null ],
    [ "WorldScene::MeshRenderData", "structWorldScene_1_1MeshRenderData.html", null ],
    [ "Mob", "classMob.html", null ],
    [ "ModelMatrice", "structModelMatrice.html", null ],
    [ "ModelMatrix_push_constant", "structModelMatrix__push__constant.html", null ],
    [ "NetworkThread", "classNetworkThread.html", null ],
    [ "ObjLoader", "classObjLoader.html", null ],
    [ "ObjVertex", "structObjVertex.html", null ],
    [ "std::ofstream", null, [
      [ "FileOutput", "classFileOutput.html", null ]
    ] ],
    [ "PacketFactory", "classPacketFactory.html", null ],
    [ "Perlin", "classPerlin.html", null ],
    [ "Pipeline", "classPipeline.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "PlayerListPacket::PlayerInfo", "structPlayerListPacket_1_1PlayerInfo.html", null ],
    [ "PlayerModel", "classPlayerModel.html", null ],
    [ "WorldScene::PlayerRenderData", "structWorldScene_1_1PlayerRenderData.html", null ],
    [ "ClientWorld::PlayerUseResult", "structClientWorld_1_1PlayerUseResult.html", null ],
    [ "Poller", "classPoller.html", null ],
    [ "PreRenderItemIconPushConstant", "structPreRenderItemIconPushConstant.html", null ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", null ],
    [ "RayCastOnBlockResult", "structRayCastOnBlockResult.html", null ],
    [ "Camera::RenderInfo", "structCamera_1_1RenderInfo.html", null ],
    [ "RenderThread", "classRenderThread.html", null ],
    [ "Sound::RIFFChunk", "structSound_1_1RIFFChunk.html", null ],
    [ "Server", "classServer.html", null ],
    [ "ServerBlockUpdateThread", "classServerBlockUpdateThread.html", null ],
    [ "ServerPacketHandler", "classServerPacketHandler.html", null ],
    [ "Settings", "classSettings.html", null ],
    [ "ShadowMapLight", "structShadowMapLight.html", null ],
    [ "SingleTimeCommand", "classSingleTimeCommand.html", null ],
    [ "Socket", "classSocket.html", [
      [ "ClientSocket", "classClientSocket.html", null ],
      [ "ConnectionSocket", "classConnectionSocket.html", null ],
      [ "ServerSocket", "classServerSocket.html", null ]
    ] ],
    [ "Status", "classStatus.html", null ],
    [ "Swapchain::SupportDetails", "structSwapchain_1_1SupportDetails.html", null ],
    [ "Swapchain", "classSwapchain.html", null ],
    [ "TextRenderer", "classTextRenderer.html", null ],
    [ "ThreadPool", "classThreadPool.html", null ],
    [ "ThreadPoolAccessor", "classThreadPoolAccessor.html", null ],
    [ "ServerWorld::Ticket", "structServerWorld_1_1Ticket.html", null ],
    [ "Timer< ChronoCount, HistorySize >", "classTimer.html", null ],
    [ "Transform", "classTransform.html", null ],
    [ "UBO", "structUBO.html", null ],
    [ "std::unordered_map", null, [
      [ "IdList< uint64_t, WorldScene::ChunkMeshRenderData >", "classIdList.html", null ],
      [ "IdList< uint64_t, WorldScene::MeshRenderData >", "classIdList.html", null ],
      [ "IdList< Key, Value, container, IdGen >", "classIdList.html", null ]
    ] ],
    [ "UpdateThread", "classUpdateThread.html", null ],
    [ "PlayerModel::Vertex", "structPlayerModel_1_1Vertex.html", null ],
    [ "ViewFrustum", "classViewFrustum.html", null ],
    [ "ViewProjMatrices", "structViewProjMatrices.html", null ],
    [ "VulkanAPI", "classVulkanAPI.html", null ],
    [ "VulkanMemoryAllocator", "classVulkanMemoryAllocator.html", null ],
    [ "PlayerModel::WalkAnimation", "classPlayerModel_1_1WalkAnimation.html", null ],
    [ "Window", "classWindow.html", null ],
    [ "World", "classWorld.html", [
      [ "ClientWorld", "classClientWorld.html", null ],
      [ "ServerWorld", "classServerWorld.html", null ]
    ] ],
    [ "WorldGenerator", "classWorldGenerator.html", null ],
    [ "WorldScene", "classWorldScene.html", null ]
];